### ISSUE TITLE
OSError:"python launcher_repoMaker.py"

### ISSUE THREAD

**Issue by disneylucy** [exatoa/Bench4BL#2]
Hi,
I'm trying to make bug repository on AspectJ.
but when I "python launcher_repoMaker.py"

[AspectJ] start making bug repositories for AspectJ
[AspectJ] loading git log data.......Done. (size:7,755 time:330)
[AspectJ] loading git versions cache....Done.
Traceback (most recent call last):
  File "launcher_repoMaker.py", line 82, in <module>
    work(args.group, args.project, args.removeTest)
  File "launcher_repoMaker.py", line 72, in work
    obj.run(S.versions[project].keys(), _removeTest)
  File "/home/sl/Bench4BL/scripts/repository/BugRepositoryMaker.py", line 251, in run
    items, dupgroups = self.bugFilter.run(logs, tagmaps, _removeTest)
  File "/home/sl/Bench4BL/scripts/repository/BugFilter.py", line 79, in run
    bugitems = self.loads()
  File "/home/sl/Bench4BL/scripts/repository/BugFilter.py", line 92, in loads
    fileConnt = self.getFileCounts(self.SourceBugPath)
  File "/home/sl/Bench4BL/scripts/repository/BugFilter.py", line 118, in getFileCounts
    files = os.listdir(_src)
OSError: [Errno 2] No such file or directory: '/home/sl/Bench4BL/data/Previous/AspectJ/bugrepo/bugs'

**Comment by exatoa** [comment]
I'm sorry too late response. 
For the previous subjects, The launcher_repoMaker.py doesn't work because we don't support it.
Actually, since some projects have no git repository or bug tracking system, we just uploaded the files which are offered from existing techniques.
